//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int idBusiness { get; set; }
        public string businessName { get; set; }
        public string RUCNumber { get; set; }
        public string businessPhone { get; set; }
        public string contactName { get; set; }
        public string contactPhone { get; set; }
        public int idUser { get; set; }
        public int idSector { get; set; }
        public string estado { get; set; }
    
        public virtual Sector Sector { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
