//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int idEvent { get; set; }
        public string name { get; set; }
        public string place { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public int idCategory { get; set; }
        public int idBusiness { get; set; }
        public string estado { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Category Category { get; set; }
    }
}
